baseURL = 'https://www.liujiayu.com/'
languageCode = 'en-us'
title = 'Jiayu Liu'
theme = 'not-much'
copyright = "All Rights Reserved © {year}"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[menu]
    [[menu.main]]
        identifier = "about"
        name = "about"
        title = "About"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "portfolio"
        name = "portfolio"
        title = "Portfolio"
        url = "/portfolio"
        weight = 2

    [[menu.main]]
        identifier = "endorsements"
        name = "endorsements"
        title = "Endorsements"
        url = "/endorsements"
        weight = 3

# Theme
[params]
theme = "auto"
palette = "catpuccin"
showThemeNotice = false
showPostsSummary = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'